VisualComposer/visual-composer-starter

js/control-toggle-switch.js

Use a prefixed ugly global

---

index.php

This PR is just an example.
Other files contain the same coding style.

Avoid touching opening and closing PHP tags

---

inc/template-tags.php

as request in #70 by @szepeviktor

Fixes #70 Add filter after usage

---

functions.php
inc/customizer/vct-customizer.class.php

Added Header Height Control <a
href="https://github.com/wpbakery/visual-composer-theme/issues/109">#109</a>

Header Height Control

---

comments.php
functions.php
inc/template-tags.php
single.php

Fixed fatal errors, so the theme could run properly for further improvements

Fixed fatal errors, so the theme could run properly

---

functions.php
inc/template-tags.php

Fix translated strings with own domain in tempate-tags.php, functions.php #116

Fix translated strings with own domain #116

---

comments.php
functions.php
inc/customizer/class-vct-customizer.php
inc/customizer/class-vct-fonts.php
inc/template-tags.php
index.php
search.php

Improved escaping, replaced __() to esc_html__() this can prevent xss injections

Fix escaping, replaced __() to esc_html__()

---

style.css

Removed the wrong tags from style.css

Fix tags regarding to WordPress standarts in style.css

---

functions.php

Fixed ACF notice, now there won' t show up any html tags.

Fix ACF install/update/activation notice

---

css/toggle-switch.css
functions.php
inc/customizer/class-vct-fonts.php
inc/customizer/controls/class-vct-toggle-switch-control.php

Fix wrong font import and fix font weight select in customizer

Fix wrong font import, fix font weight

---

header.php
inc/template-tags.php
template-parts/content-gallery.php

Remove alt tags, and load the logo by using default WordPress function

Remove alt tags

---

404.php
archive.php
comments.php
footer.php
functions.php
header.php
inc/class-visualcomposerstarter-update.php
inc/customizer/class-visualcomposerstarter-customizer.php
inc/customizer/class-visualcomposerstarter-fonts.php
inc/customizer/controls/class-vct-toggle-switch-control.php
inc/hooks.php
inc/template-tags.php
index.php
page.php
search.php
sidebar.php
single.php
template-parts/content-page.php
template-parts/content-single.php

Update prefixes #523856791520135

---

inc/customizer/class-visualcomposerstarter-customizer.php

Currently 'vct_content_area' has added settings (line: 400), but the section isn't registered in the customizer

Register missing theme section

---

functions.php

Won't include the main style.css, will leave it just as an info file for theme header. The main style will be css/style.css

Use only one style.css #61

---

functions.php

Reverts wpbakery/visual-composer-starter#212 
Because of a broken child theme.

Revert "Use only one style.css #61"

---

inc/customizer/class-visualcomposerstarter-customizer.php

Changed body font-family sanitize callback from "sanitize_select" to "sanitize_select_google_fonts"

Fixed so body font-family may be edited

---

header.php

Implement Wordpress 5.2.0 feature
https://developer.wordpress.org/reference/functions/wp_body_open/

Fire the wp_body_open action.

---

functions.php

Updated widgets closing tag to a correct one: `</h3>`

Update widgets markup #252

---

functions.php
inc/customizer/class-visualcomposerstarter-customizer.php
languages/visual-composer-starter.pot

Added options inside Customizer under Theme Options for:
- Tag Background
- Tag Background Hover
- Tag Color
- Tag Color Hover

Add tag color and background color settings to Customizer #238

---

woocommerce/cart/cart.php
woocommerce/checkout/review-order.php
woocommerce/checkout/thankyou.php
woocommerce/notices/error.php
woocommerce/notices/notice.php
woocommerce/notices/success.php
woocommerce/order/order-details-item.php
woocommerce/order/order-details.php

Adjust WooCommerce compatibility VisualComposer#264

Adjust WooCommerce compatibility VisualComposer#264

---

functions.php

Add exists checks for functions.php VisualComposer#236

Add exists checks for functions.php VisualComposer#236

---

woocommerce/global/quantity-input.php

Woocommerce compatibility

---

js/functions.js

Remove extra space in aria-label

---

functions.php
inc/customizer/class-visualcomposerstarter-fonts.php

Fix issues with Google Fonts

---

css/customizer-custom.css
functions.php
inc/customizer/class-visualcomposerstarter-customizer.php
inc/customizer/class-visualcomposerstarter-fonts.php
inc/customizer/controls/class-visualcomposerstarter-google-fonts-control.php
js/control-google-fonts.js
js/control-select.js
js/customize-popup.js

Google Font Store Locally
